apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: rhel9-gitops2
      app2: db
      vm.kubevirt.io/template: rhel9-server-small
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: v0.14.0
    name: rhel9-gitops2
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel9-gitops2
      spec:
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 32Gi
          storageClassName: vroom
        source:
          pvc:
            name: rhel92
            namespace: kubevirt-gitops
    running: true
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: small
          vm.kubevirt.io/os: rhel9
          vm.kubevirt.io/workload: server
        labels:
          kubevirt.io/domain: rhel9-gitops2
          kubevirt.io/size: small
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: rhel9-gitops1
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
#            - name: default
#              masquerade: {}
            - name: lab-network
              bridge: {}
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.4.0
          resources:
            requests:
              memory: 2Gi
        evictionStrategy: LiveMigrate
        networks:
#        - name: default
#          pod: {}
        - name: lab-network 
          multus:
            networkName: lab-network
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: rhel9-gitops2
          name: rhel9-gitops2
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: johan 
              password: redhat123!
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}
